Use UTF8 for reporting compile error for Rust frontend
mozilla-spidermonkey/rust-frontend pull request #30
Opened 2020-01-29 01:23 UTC by arai-a

maybe we can rename existing `ReportCompileError` to `ReportCompileErrorLatin1`, but I'll leave it as is, to avoid modifying mostly unrelated place in this repository.

2020-01-30 14:12 UTC, arai-a commented
If things will be merged to m-c shortly, I guess renaming existing ReportCompileError to ReportCompileErrorLatin1 is better.
will fix patch shortly.

2020-02-04 21:00 UTC, jorendorff requested changes
Let's upstream this right away. Please close this PR and re-file as a bugzilla bug.

2020-02-04 23:57 UTC, arai-a commented
Moved most part to https://bugzilla.mozilla.org/show_bug.cgi?id=1613270
I'll update this to use UTF8 variant in Frontend2.cpp

2020-02-05 04:30 UTC, jorendorff approved these changes

2020-02-05 04:32 UTC, jorendorff commented
Looks good. Assuming bug 1613270 lands in mozilla-central without problems, I'll merge that to rust-frontend sometime tomorrow (~12 hours from now), then land this.

2020-02-05 17:43 UTC, merged